language: node_js
cache:
  directories:
    - ~!@/.npm
git:
  depth: 3
scripts: 
  -yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: \$GITHUB-TOKEN
  local-dir: dist/
  target-branch: master
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on: 
    branch: develop